modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/ChaosAwakens/ChaosAwakens/issues"
license="All Rights Reserved."

[[mods]]
modId="chaosawakens"
version="${file.jarVersion}"
displayName="Chaos Awakens"
updateJSONURL="https://raw.githubusercontent.com/ChaosAwakens/ChaosAwakens/1.16.5-forge/update.json"
displayURL="https://chaosawakens.github.io/#downloadsDiv"
authors="Chaos Team"
description='''Relive the old Orespawn from 1.7.10 in newer Minecraft versions!'''
logoFile="logo.png"
itemIcon="chaosawakens:ultimate_pickaxe"
configBackground="chaosawakens:textures/gui/advancement_bg.png"

[[dependencies.chaosawakens]]
modId="forge"
mandatory=true
versionRange="[36.2.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="geckolib3"
mandatory=true
versionRange="[3.0.90,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="patchouli"
mandatory=true
versionRange="[1.16.4-53,)"
ordering="AFTER"
side="BOTH"

[[dependencies.chaosawakens]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"

[[dependencies.chaosawakens]]
modId="jeresources"
mandatory=false
versionRange="[0.12,]"
ordering="AFTER"
side="BOTH"
