modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Chaos-Awakens-Mod-Team/ChaosAwakens/issues"
displayURL="https://chaosawakens.github.io/downloads.html"
license="All Rights Reserved. Code from before v0.9 is licensed GNU LGPL v2.1."

[[mods]]
modId="chaosawakens"
version="${file.jarVersion}"
displayName="Chaos Awakens"
authors="Chaos Team"
description='''Relive the old OreSpawn mod in newer Minecraft versions!'''
itemIcon="chaosawakens:ultimate_pickaxe"
configBackground="chaosawakens:textures/gui/advancement_bg.png"

[[dependencies.chaosawakens]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"

[[dependencies.chaosawakens]]
modId="jeresources"
mandatory=false
versionRange="[0.12,]"
ordering="AFTER"
side="BOTH"
